---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBpClI+9O0CaVZRDU9VfYGrvgiHsmz7Aiu2UwiGdUuPs7aIc4+Y5ePaOOxlUcoaKDh2QCpNkQdqEiIi851sgg/9koj/GGduHKeOiHiXoiRoEF/0961wSID8WMTYBsKkoIVeacRqAZRZkkRnOnNNs6x2pC7+vVuMncqfC5nQi0jbEKLjTvxfh/7Tr4Qj3s10Q3FPpBvxtc5Vm7gM1DKGkOtYWft6cNpWqgY0ZyJyPcMVG3Gs5PZrD3e2BgE3PE3SANda3GnWd5midXNpxhdUN6vn6j70RChOrbZLExMlRNL+c1ek6dz/L5s4xDsCjf6NAEABjjerhlJ4xN9BWb095itUMGkbKTQ+u/Gh6+xVu4ruLaz8JFWSXhvCtrQHZLU1xw8Oi3PTOF8ZLo86hJ4GWNUv02LNDksjUXJgwsc7qkGYDm0VKe5ctkqJrcSr8mzb/OF8Kt7NliA/p3EtA3eBCFhvkEbwj5HS7kI+zVpbnpFqk3TslVLEjS9SxJd+KU10YKXLul2nRshRtT6m0aMcZs0di5tHnt/I9NVkW3C+JY4gLppa/vlYpNYWf9j2s1t1rRdBWT7zAgmetHPZarmhzpS5xg0K9XdQItgNpb2lNBUfphqNQVJH9e0ATXLusDBtdTwfNQVXSOUcJ/ve6LnQTwaSsjG+iZ8a8y/CbAyKmf3KW6B4kRzDMt5jvIFcpl18YCvFrjuuIskVNsTEQGaF
    admin-user: AgB03qeufNwZ95YikGOh/7tdwWXyXIJaQf6bJjQrAlDEPHMYp2iUOqzF7++Rl8YkbFdXtLaNxAPmOsft5d5gn3M7d0gLtQXMnYf4rht6ixrCwlJSNEUZilDASBAchMqjl7qYCCJ2ZNeFWdkLLWJbyOUmo05VpP0WWc+RYWO3ND79H6UstCjIeVnf4GuxdI4oXf/QX0TLmDon4xw49OfkPqzl9U4D53Zj3S3kKiBtZjvNAp3+qUZAu+hOJ6UrMI6vJ2P7cv0HU+rKORJh25u0JvU0Qn0sIzAlaVFjkKADzJy9jUBTTtTzld8CLUaWbz2gT54JvhjBRUNLvN+WA51WdLspYT4ItEVR1gHq5fOZIiM3J7TQtNnTzIKSDzRXm3C+L/DtCpCxyDhCFmUbVu750Buwsw1QAB9SEg2BSFsHqRxhxQGCADWZTHe3LAEwT6xh061DMjnpOblZJ5AngxM+bDJMdEFGZwzzJ8RYRpGy1pEZSaofXQ4CtQDR46f1EDCHSrH1aJ8ubKF3ftB0+edB0hqvvwvgYex1HMfOjxMq8P5BSvFuuiOYIid/vGJXPwRyd3nOgjyQ+nkjKjgC9HWa5SGAftmDP6wEDhGKml0a2sLMIvhMJuKTBgrzTV9ODyZBQxbf0zFVhO8+BAnESMo6Lea7w+uESUMp/NimbCBNCIXz2upFx3cnCsXyTxt6yrLUfvKF+4mfRw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
